### ISSUE TITLE
Backlinks audit should validate whether broken backlink is fixed already

### ISSUE THREAD

**Issue by solaris007** [adobe/spacecat-audit-worker#133]
Due to the long re-indexing times of the primary broken backlinks source `ahrefs`, results should be validated whether they're already fixed by visiting the broken backlink and excluding from the result if fixed. This is to prevent false positives in the report after people have fixed the links.

**Comment by 7r0u8l3** [comment]
Hi, Im new to SC and dev but have talked to Meryll and will work on this ticket but I still need access to SC AWS. Ive requested access in IAM. Need that so I can start testing code. Assigning to me in meantime. Thanks!
