### ISSUE TITLE
All audit types handlers should use the shared isAuditDisabled check

### ISSUE THREAD

**Issue by iuliag** [adobe/spacecat-audit-worker#187]
**Description**
Each handler uses the own logic to check if audit is disabled.

**Expected behavior**
All audit types handlers should use the shared isAuditDisabled check, after team convenes how the disabling should work for org and site level.

**Additional context**
https://github.com/adobe/spacecat-shared/blob/main/packages/spacecat-shared-utils/src/helpers.js#L39

**Asks that could have been solved by the feature**
https://cq-dev.slack.com/archives/C05A45JBP9N/p1710871764208859

**Comment by solaris007** [comment]
this seems to be included in the new `AuditBuilder` https://github.com/adobe/spacecat-audit-worker/pull/136

cc @ekremney
