### ISSUE TITLE
Migrate experimentation to AuditBuilder

### ISSUE THREAD

**Issue by alinarublea** [adobe/spacecat-audit-worker#202]
As per [architecture meeting](https://github.com/adobe-rnd/spacecat-infrastructure-docs/wiki/Architecture-Meetings#3-moving-existing-audits-to-the-new-auditbuilder-way---ekrem) migrate existing audits to the new AuditBuilder.

This issue is for migration of the Experimentation audit

**Comment by ekremney** [comment]
fixed by @raji-unni via https://github.com/adobe/spacecat-audit-worker/pull/211
