### ISSUE TITLE
Migrate Sitemap to AuditBuilder

### ISSUE THREAD

**Issue by dzehnder** [adobe/spacecat-audit-worker#204]
As per [architecture meeting](https://github.com/adobe-rnd/spacecat-infrastructure-docs/wiki/Architecture-Meetings#3-moving-existing-audits-to-the-new-auditbuilder-way---ekrem) migrate existing audits to the new AuditBuilder.

This issue is for migration of the Sitemap audit.

**Comment by ekremney** [comment]
fixed by @AndreiAlexandruParaschiv via https://github.com/adobe/spacecat-audit-worker/pull/238
