### ISSUE TITLE
Find bad urls in the sitemap

### ISSUE THREAD

**Issue by amol-anand** [adobe/spacecat-audit-worker#235]
**Is your feature request related to a problem? Please describe.**
We had an issue recently where there was an empty row in the query-index that resulted in a url in the sitemap looking like this:
`newsroom.accenture.sg0` (the 0 came from the formula in helix-default sheet that was filtering stuff from raw_index)

**Describe the solution you'd like**
It would be great if you can check the validity of the links in the sitemap and see if they actually work or are wrong (especially a 0 instead of the path after the domain name seems like something that could happen if there was an empty row by mistake in the raw_index)

**Describe alternatives you've considered**
Customer find the issue and reports it to us and we fixed it. This is what happened. But I would like to be proactive about it instead of reactive.

Already synced with Ekrem and DJ on this.

**Comment by AndreiAlexandruParaschiv** [comment]
Fix with https://github.com/adobe/spacecat-audit-worker/pull/238 and https://github.com/adobe/spacecat-audit-worker/pull/266
